### ISSUE TITLE
Korean translation for AE 'neighborhood.optional' label is incorrect

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/worldwide#304]
https://github.com/Shopify/worldwide/pull/303 incorrectly updated the korean label for `worldwide.AE.addresses.neighborhood.label.optional` from "면적(선택 사항)" (Google translates as _Area (optional)_) to "Area(마카오 행정구역, 선택 사항)" (Google translates as _Area (Macau administrative district, optional)_).

Non-english translations should not be manually corrected. I left the error in PR 303, and I am opening this issue to track the correction in the upstream translation platform.

**Comment by MRodriguezRod** [comment]
@rochlefebvre Resolved on the localization side.

**Comment by rochlefebvre** [comment]
Fixed by https://github.com/Shopify/worldwide/pull/310
