### ISSUE TITLE
Greek translation for AR 'province.default' label is incorrect

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/worldwide#306]
https://github.com/Shopify/worldwide/pull/303 incorrectly updated the greek label for `worldwide.AR.addresses.province.label.default` from "Επαρχία" (Google translates as _Province_) to "Νομός" (Google translates as _law, county, statute, department_). The old translation is likely more accurate since Argentina has [provinces](https://en.wikipedia.org/wiki/Provinces_of_Argentina).

Non-english translations should not be manually corrected. I left the error in PR 303, and I am opening this issue to track the correction in the upstream translation platform.

**Comment by MRodriguezRod** [comment]
@rochlefebvre - Resolved on the Localization side.

**Comment by rochlefebvre** [comment]
Fixed by https://github.com/Shopify/worldwide/pull/310
