### ISSUE TITLE
Croatian translation for AU 'zip.optional' label is incorrect

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/worldwide#308]
https://github.com/Shopify/worldwide/pull/303 correctly updated the croatian label for `worldwide.AU.addresses.zip.label.default` from "Poštanski broj" (Google translates as _Zip code_) to "Poštanski kod" (Google translates as _Postal code_). The neighboring `worldwide.AU.addresses.zip.label.optional` key should also be updated, from _zip_ to _postal_.

Non-english translations should not be manually corrected. I left the error in PR 303, and I am opening this issue to track the correction in the upstream translation platform.

**Comment by MRodriguezRod** [comment]
@rochlefebvre - Resolved on the Localization side.

**Comment by rochlefebvre** [comment]
Fixed by https://github.com/Shopify/worldwide/pull/310
